version: '3.5'

services:
  db:
    container_name: student-ms
    image: postgres
    environment:
      POSTGRES_USER: vedad
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: